version: '3.7'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/workdir
    ports:
      - 8000:4040
      - 8001:4041
      - 8888:8888  # for notebooks
    entrypoint: "tail -f /dev/null"